Cleanup

diff --git a/setjobenv/action.yml b/setjobenv/action.yml
--- a/setjobenv/action.yml
+++ b/setjobenv/action.yml
@@ -3,37 +3,52 @@ description: "Sets usable env for all job steps based on payload in GitHub Event
 runs:
   using: "composite"
   steps:
-    - name: Check Dependencies
+    - name: Check Dependencies (Linux)
+      if: runner.os == 'Linux'
       run: |
         packagesNeeded='curl jq gh'
         SUDO=$(command -v sudo)
         if [ -x "$(command -v apk)" ]; then
             $SUDO apk add --no-cache $packagesNeeded
         elif [ -x "$(command -v apt-get)" ]; then
-            type -p curl >/dev/null || sudo apt install curl -y
-            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
-            && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
-            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-            && sudo apt update \
-            && $SUDO apt-get install -y $packagesNeeded
+            type -p curl >/dev/null || $SUDO apt install curl -y
+            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
+            $SUDO dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+            $SUDO chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
+            $SUDO tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+            $SUDO apt update
+            $SUDO apt-get install -y $packagesNeeded
         elif [ -x "$(command -v dnf)" ]; then
-            sudo dnf install 'dnf-command(config-manager)'
-            sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
+            $SUDO dnf install 'dnf-command(config-manager)'
+            $SUDO dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
             $SUDO dnf install -y $packagesNeeded
         elif [ -x "$(command -v zypper)" ]; then
-            sudo zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
-            sudo zypper ref
+            $SUDO zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
+            $SUDO zypper ref
             $SUDO zypper install -n $packagesNeeded
         elif [ -x "$(command -v pacman)" ]; then
             $SUDO pacman -S --needed --noconfirm $packagesNeeded
-        elif [ -x "$(command -v brew)" ]; then
-            brew install $packagesNeeded
-        elif [ -x "$(command -v chocolatey)" ]; then
-            choco install -y $packagesNeeded
         else
             echo "FAILED TO INSTALL required packages: $packagesNeeded" >&2
         fi
       shell: bash
+    - name: Check Dependencies (macOS)
+      if: runner.os == 'macOS'
+      run: |
+        packagesNeeded='curl jq gh'
+        if [ -x "$(command -v brew)" ]; then
+            brew install $packagesNeeded
+        else
+            echo "FAILED TO INSTALL required packages: $packagesNeeded" >&2
+        fi
+      shell: bash
+    - name: Check Dependencies (Windows)
+      if: runner.os == 'Windows'
+      run: |
+        $env:packagesNeeded='curl jq gh'
+        choco install -y $env:packagesNeeded
+      shell: powershell
     - name: Identify Runner Hardware (Linux)
       if: runner.os == 'Linux' && runner.arch == 'X86' || runner.os == 'Linux' && runner.arch == 'X64'
       shell: bash
@@ -126,17 +141,18 @@ runs:
 
         # These are needed first for some of the functions and conditionals within this action
         REPO=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f2)
-        #LANGUAGE=$(gh api repos/"$GITHUB_REPOSITORY" --jq '.language')
+        LANGUAGE=$(gh api repos/"$GITHUB_REPOSITORY" --jq '.language')
         RFC_REPO=$(echo "$REPO" | sed 's/\./-/g; s/_/-/g')
         GIT_SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-8)
         GH_EVENT_ACTION=${{ github.event.action }}
 
         # Pre-Release/Release logic
         if [ "$GITHUB_EVENT_NAME" == 'release' ] && [ "$GH_EVENT_ACTION" == 'published' ]; then
+            RELEASE=true
             PRE_RELEASE=$(jq -r '.release.prerelease' "$GITHUB_EVENT_PATH")
             RELEASE_TAG=$(jq -r '.release.tag_name' "$GITHUB_EVENT_PATH")
             {
-              echo "RELEASE=true"
+              echo "RELEASE=$RELEASE"
               echo "PRE_RELEASE=$PRE_RELEASE"
               echo "RELEASE_TAG=$RELEASE_TAG"
             } >> "$GITHUB_ENV"
@@ -154,8 +170,8 @@ runs:
         # Begin custom
         echo "GH_EVENT_ACTION=$GH_EVENT_ACTION" >>GITHUB_ENV
         echo "Set GH_EVENT_ACTION=$GH_EVENT_ACTION"
-        #echo "LANGUAGE=$LANGUAGE" >>$GITHUB_ENV
-        #echo "Set LANGUAGE=$LANGUAGE"
+        echo "LANGUAGE=$LANGUAGE" >>$GITHUB_ENV
+        echo "Set LANGUAGE=$LANGUAGE"
         echo "GH_WORKFLOW_URL="$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY"/actions/runs/"$GITHUB_RUN_ID"" >>$GITHUB_ENV
         echo "Set GH_WORKFLOW_URL=$GH_WORKFLOW_URL"
         # RFC_REPO: the repo name represented in a RFC1035 format
