Revert "Printing out job vars"

diff --git a/setjobenv/action.yml b/setjobenv/action.yml
--- a/setjobenv/action.yml
+++ b/setjobenv/action.yml
@@ -1,30 +1,17 @@
-name: "⚙️ Set Job Environment"
+name: "Set Job Environment"
 description: "Sets usable env for all job steps based on payload in GitHub Event. To be ran immediately after 'actions/checkout' step."
 runs:
   using: "composite"
   steps:
     - name: Check Dependencies
       run: |
-        packagesNeeded='curl jq'
-        if [ -x "$(command -v apk)" ]; then
-            apk add --no-cache $packagesNeeded
-        elif [ -x "$(command -v apt-get)" ]; then
-            apt-get update && apt-get install -y $packagesNeeded
-        elif [ -x "$(command -v dnf)" ]; then
-            dnf install -y $packagesNeeded
-        elif [ -x "$(command -v zypper)" ]; then
-            zypper install -n $packagesNeeded
-        elif [ -x "$(command -v pacman)" ]; then
-            pacman -S --needed --noconfirm $packagesNeeded
-        elif [ -x "$(command -v brew)" ]; then
-            brew install $packagesNeeded
-        elif [ -x "$(command -v chocolatey)" ]; then
-            choco install -y $packagesNeeded
-        else
-            echo "FAILED TO INSTALL required packages: $packagesNeeded" >&2
+        if ! command -v jq &> /dev/null; then
+          echo "ERROR: Missing jq"
+          echo "Install it from your package manager, or get it at https://github.com/stedolan/jq"
+          exit 1
         fi
       shell: bash
-    - name: Set & Print ENV
+    - name: Check Dependencies
       run: |
         echo "GitHub native job envs:"
         echo "――――――――――――――――――――――"
@@ -65,58 +52,72 @@ runs:
         echo "RUNNER_TEMP="$RUNNER_TEMP
         echo "RUNNER_TOOL_CACHE="$RUNNER_TOOL_CACHE
         echo "――――――――――――――――――――――"
-        echo "Setting env for steps:"
-        echo "――――――――――――――――――――――"
-
-        # These are needed first for some of the functions and conditionals within this action
+        # These are needed for some of the functions and conditionals within this action
         REPO=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f2)
         LANGUAGE=$(curl -s -X GET https://"$GPR_TOKEN":@api.github.com/repos/"$GITHUB_REPOSITORY" | jq -r '.language')
         RFC_REPO=$(echo "$REPO" | sed 's/\./-/g; s/_/-/g')
         GIT_SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-8)
         GH_EVENT_ACTION=${{ github.event.action }}
-
         # Pre-Release/Release logic
         if [ "$GITHUB_EVENT_NAME" == 'release' ] && [ "$GH_EVENT_ACTION" == 'published' ]; then
-            PRE_RELEASE=$(jq -r '.release.prerelease' "$GITHUB_EVENT_PATH")
-            RELEASE_TAG=$(jq -r '.release.tag_name' "$GITHUB_EVENT_PATH")
-            {
-              echo "RELEASE=true"
-              echo "PRE_RELEASE=$PRE_RELEASE"
-              echo "RELEASE_TAG=$RELEASE_TAG"
-            } >> "$GITHUB_ENV"
-            if [ "$PRE_RELEASE" = false ]; then
-                echo "FULL_RELEASE=true" >>"$GITHUB_ENV"
-            else
-                echo "FULL_RELEASE=false" >>"$GITHUB_ENV"
-            fi
-          echo "Set RELEASE=$RELEASE"
-          echo "Set PRE_RELEASE=$PRE_RELEASE"
-          echo "Set RELEASE_TAG=$RELEASE_TAG"
-          echo "Set FULL_RELEASE=$FULL_RELEASE"
+          PRE_RELEASE=$(jq -r '.release.prerelease' "$GITHUB_EVENT_PATH")
+          RELEASE_TAG=$(jq -r '.release.tag_name' "$GITHUB_EVENT_PATH")
+          {
+            echo "RELEASE=true"
+            echo "PRE_RELEASE=$PRE_RELEASE"
+            echo "RELEASE_TAG=$RELEASE_TAG"
+          } >> "$GITHUB_ENV"
+          if [ "$PRE_RELEASE" = false ]; then
+            echo "FULL_RELEASE=true" >>"$GITHUB_ENV"
+          else
+            echo "FULL_RELEASE=false" >>"$GITHUB_ENV"
+          fi
         fi
-
         # Begin custom
-        echo "GH_EVENT_ACTION=$GH_EVENT_ACTION" >>GITHUB_ENV
-        echo "Set GH_EVENT_ACTION=$GH_EVENT_ACTION"
-        echo "LANGUAGE=$LANGUAGE" >>$GITHUB_ENV
-        echo "Set LANGUAGE=$LANGUAGE"
-        echo "GH_WORKFLOW_URL="$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY"/actions/runs/"$GITHUB_RUN_ID"" >>$GITHUB_ENV
-        echo "Set GH_WORKFLOW_URL=$GH_WORKFLOW_URL"
-        # RFC_REPO: the repo name represented in a RFC1035 format
-        # which is useful if you want the repo name = a valid k8s namespace/service/deployment etc.
+        echo "Setting env for steps:"
+        echo "――――――――――――――――――――――"
+        echo "GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >>$GITHUB_ENV
+        echo "Set GITHUB_WORKFLOW_URL=$GITHUB_WORKFLOW_URL"
+        # Repo name represented in a RFC1035 format - useful if you want the repo name = k8s namespace/service/deployment etc
         echo "RFC_REPO=$RFC_REPO" >>$GITHUB_ENV
         echo "Set RFC_REPO=$RFC_REPO"
         echo "GIT_SHORT_HASH=$GIT_SHORT_HASH" >>$GITHUB_ENV
         echo "Set GIT_SHORT_HASH=$GIT_SHORT_HASH"
-        # GPR_PROJECT: Use if you want to publish artifacts to GitHub Package Repository
-        export GPR_PROJECT=ghcr.io/$GITHUB_REPOSITORY_OWNER/$REPO
+        # For publishing artifacts to GitHub Package Repository
+        export GPR_PROJECT=docker.pkg.github.com/$GITHUB_REPOSITORY_OWNER/$REPO
         echo "GPR_PROJECT=$GPR_PROJECT" >>$GITHUB_ENV
         echo "Set GPR_PROJECT=$GPR_PROJECT"
         export REVISION=${GITHUB_REF##*/}
         echo "REVISION=$REVISION" >>$GITHUB_ENV
         echo "Set REVISION=$REVISION"
-        # ADD YOUR OWN ENVS BELOW
+        # TODO: see if the below sections are wanted as input conditions
+        # # For Dockerhub, uncomment the following block
+        # export DHREPO_NAME=$GITHUB_REPOSITORY_OWNER/$REPO
+        # echo "DHREPO_NAME=$DHREPO_NAME" >>$GITHUB_ENV
+        # echo "Set DHREPO_NAME=$DHREPO_NAME"
         #
+        # export DHIMAGE_TAG="$DHREPO_NAME:$GIT_SHORT_HASH"
+        # echo "DHIMAGE_TAG=$DHIMAGE_TAG" >>$GITHUB_ENV
+        # echo "Set DHIMAGE_TAG=$DHIMAGE_TAG"
+        #
+        # export DHIMAGE_VERSION="$RELEASE_VERSION"
+        # echo "DHIMAGE_VERSION=$DHIMAGE_VERSION" >>$GITHUB_ENV
+        # echo "Set DHIMAGE_VERSION=$DHIMAGE_VERSION"
+        #
+        # export DHIMAGE_TAG_VERSION="$DHREPO_NAME:$DHIMAGE_VERSION"
+        # echo "DHIMAGE_TAG_VERSION=$DHIMAGE_TAG_VERSION" >>$GITHUB_ENV
+        # echo "Set DHIMAGE_TAG_VERSION=$DHIMAGE_TAG_VERSION"
+        #
+        # export DOCKER_BUILDKIT=1
+        # echo "DOCKER_BUILDKIT=$DOCKER_BUILDKIT" >>$GITHUB_ENV
+        # echo "Set DOCKER_BUILDKIT=$DOCKER_BUILDKIT"
+        # #
+        # # If using remote Docker host, uncomment the following block
+        # export DOCKER_HOST=tcp://my-remote.docker-host.tld:2376
+        # echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
+        #
+        # export DOCKER_TLS_VERIFY=1
+        # echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY" >> $GITHUB_ENV
         echo "――――――――――――――――――――――"
         echo "Complete"
       shell: bash
