Adding conditional to package install

diff --git a/setjobenv/action.yml b/setjobenv/action.yml
--- a/setjobenv/action.yml
+++ b/setjobenv/action.yml
@@ -5,12 +5,24 @@ runs:
   steps:
     - name: Check Dependencies
       run: |
-        ( command -v apk && apk add jq ) || true
-        ( command -v apt-get && apt-get update && apt-get install -y jq ) || true
-        ( command -v dnf && dnf install jq ) || true
-        ( command -v pacman && pacman -S jq ) || true
-        ( command -v brew && brew install jq ) || true
-        ( command -v chocolatey && chocolatey install jq ) || true
+        packagesNeeded='curl jq'
+        if [ -x "$(command -v apk)" ]; then
+            apk add --no-cache $packagesNeeded
+        elif [ -x "$(command -v apt-get)" ]; then
+            apt-get update && apt-get install -y $packagesNeeded
+        elif [ -x "$(command -v dnf)" ]; then
+            dnf install -y $packagesNeeded
+        elif [ -x "$(command -v zypper)" ]; then
+            zypper install -n $packagesNeeded
+        elif [ -x "$(command -v pacman)" ]; then
+            pacman -S --needed --noconfirm $packagesNeeded
+        elif [ -x "$(command -v brew)" ]; then
+            brew install $packagesNeeded
+        elif [ -x "$(command -v chocolatey)" ]; then
+            choco install -y $packagesNeeded
+        else
+            echo "FAILED TO INSTALL required packages: $packagesNeeded" >&2
+        fi
       shell: bash
     - name: Set & Print ENV
       run: |
