Add basic http status code response checks to vault actions

diff --git a/vault/k8s-login/action.yml b/vault/k8s-login/action.yml
--- a/vault/k8s-login/action.yml
+++ b/vault/k8s-login/action.yml
@@ -30,25 +30,36 @@ runs:
       shell: sh
     - name: Get certificate
       run: |
-        DATA=$(curl -s \
+        temp_file=$(mktemp)
+        http_status=$(curl -s \
           --header "X-Vault-Token: ${{ inputs.vault_token }}" \
           --request POST \
+          -o ${temp_file} \
+          -w "%{http_code}" \
           --data "{\"ttl\":\"${{ inputs.ttl }}\",\"common_name\":\"${{ github.actor }}@github\"}" \
           ${{ inputs.vault_url }}/v1/${{ inputs.backend_name }}/issue/${{ inputs.role_name }})
 
-        # Write the key data to a temp file
-        CERT_FILE=$(mktemp)
-        KEY_FILE=$(mktemp)
-        printf '%s' "$DATA" | jq -r '.data.certificate' > $CERT_FILE
-        printf '%s' "$DATA" | jq -r '.data.private_key' > $KEY_FILE
+        DATA=$(cat ${temp_file})
+        rm -f ${temp_file}
 
-        # Generate a kubeconfig with the provided data
-        kubectl config set-cluster 'cluster' --server=${{ inputs.cluster_url }}
-        kubectl config set clusters.cluster.certificate-authority-data "$(printf '%s' "$DATA" | jq -r '.data.issuing_ca' | base64)"
-        kubectl config set-credentials 'cluster-user' --embed-certs=true --client-certificate="$CERT_FILE" --client-key="$KEY_FILE"
-        kubectl config set-context 'cluster' --cluster=cluster --user=cluster-user
-        kubectl config use-context 'cluster'
+        if [ $http_status -ge 200 ] && [ $http_status -le 299 ]; then
+          # Write the key data to a temp file
+          CERT_FILE=$(mktemp)
+          KEY_FILE=$(mktemp)
+          printf '%s' "$DATA" | jq -r '.data.certificate' > $CERT_FILE
+          printf '%s' "$DATA" | jq -r '.data.private_key' > $KEY_FILE
 
-        rm -f $CERT_FILE || true
-        rm -f $KEY_FILE || true
+          # Generate a kubeconfig with the provided data
+          kubectl config set-cluster 'cluster' --server=${{ inputs.cluster_url }}
+          kubectl config set clusters.cluster.certificate-authority-data "$(printf '%s' "$DATA" | jq -r '.data.issuing_ca' | base64)"
+          kubectl config set-credentials 'cluster-user' --embed-certs=true --client-certificate="$CERT_FILE" --client-key="$KEY_FILE"
+          kubectl config set-context 'cluster' --cluster=cluster --user=cluster-user
+          kubectl config use-context 'cluster'
+
+          rm -f $CERT_FILE || true
+          rm -f $KEY_FILE || true
+        else
+          echo "Error: HTTP Status Code return ${http_status}"
+          exit 1
+        fi
       shell: sh
diff --git a/vault/login/action.yml b/vault/login/action.yml
--- a/vault/login/action.yml
+++ b/vault/login/action.yml
@@ -15,8 +15,16 @@ runs:
     - name: Get credentials from vault
       shell: sh
       run: |
-        creds=$(curl -s --request POST -d "{\"jwt\":\"$JWT_TOKEN\",\"role\":\"${{ inputs.role_name }}\"}" ${{ inputs.vault_url }}/v1/auth/github-jwt/login)
+        temp_file=$(mktemp)
+        http_status=$(curl -s -o ${temp_file} -w "%{http_code}" --request POST -d "{\"jwt\":\"$JWT_TOKEN\",\"role\":\"${{ inputs.role_name }}\"}" ${{ inputs.vault_url }}/v1/auth/github-jwt/login)
+        creds=$(cat ${temp_file})
+        rm -f ${temp_file}
 
-        VAULT_TOKEN=$(echo $creds | jq -r '.auth.client_token')
-        echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
-        echo "::add-mask::$VAULT_TOKEN"
+        if [ $http_status -ge 200 ] && [ $http_status -le 299 ]; then
+          VAULT_TOKEN=$(echo $creds | jq -r '.auth.client_token')
+          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
+          echo "::add-mask::$VAULT_TOKEN"
+        else
+          echo "Error: HTTP Status Code return ${http_status}"
+          exit 1
+        fi
diff --git a/vault/signed-ssh-key/action.yml b/vault/signed-ssh-key/action.yml
--- a/vault/signed-ssh-key/action.yml
+++ b/vault/signed-ssh-key/action.yml
@@ -54,11 +54,22 @@ runs:
     - name: Sign key
       run: |
         PUBLIC_KEY=$(cat ${{ inputs.keypair_path }}.pub)
-        data=$(curl -s \
+
+        temp_file=$(mktemp)
+        http_status=$(curl -s \
           --header "X-Vault-Token: ${{ inputs.vault_token }}" \
           --request POST \
+          -o ${temp_file} \
+          -w "%{http_code}" \
           --data "{\"public_key\":\"$PUBLIC_KEY\",\"ttl\":\"${{ inputs.ttl }}\"}" \
           ${{ inputs.vault_url }}/v1/${{ inputs.backend_name }}/sign/${{ inputs.role_name }})
+        data=$(cat ${temp_file})
+        rm -f ${temp_file}
 
-        echo $data | tr -d '\n' | jq -r '.data.signed_key' > ${{ inputs.keypair_path }}-cert.pub
+        if [ $http_status -ge 200 ] && [ $http_status -le 299 ]; then
+          echo $data | tr -d '\n' | jq -r '.data.signed_key' > ${{ inputs.keypair_path }}-cert.pub
+        else
+          echo "Error: HTTP Status Code return ${http_status}"
+          exit 1
+        fi
       shell: sh
