add diagnostics for pyenv installation in setup-python action

diff --git a/setup-python/action.yml b/setup-python/action.yml
--- a/setup-python/action.yml
+++ b/setup-python/action.yml
@@ -82,19 +82,25 @@ runs:
       if: runner.arch == 'ARM64' || inputs.force-pyenv != 'false'
       shell: sh
       run: |
-        unset PYENV_ROOT
-
-        if [ ! -d "$HOME/.pyenv" ]; then
+        export PYENV_ROOT="$HOME/.pyenv"
+        echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
+        
+        if [ ! -d "$PYENV_ROOT" ]; then
+          echo "installing pyenv at: $PYENV_ROOT"
           curl https://pyenv.run | bash
+        else
+          echo "pyenv directory found at: $PYENV_ROOT"
         fi
         
         export PATH="$HOME/.pyenv/bin:$PATH"
         echo "PATH=$HOME/.pyenv/bin:$PATH" >> $GITHUB_ENV
         
-        export PYENV_ROOT="$HOME/.pyenv"
-        echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
-        
         # Ensure pyenv is up to date
+        if ! type pyenv &> /dev/null; then
+          type pyenv
+          echo "pyenv executable not found, dumping tree of: $PYENV_ROOT"
+          tree "$PYENV_ROOT"
+        fi
         pyenv update
         
         FULL_PY_VERSION=$(pyenv install --list | grep "^  ${{ inputs.python-version }}" | grep -v 'dev' | tail -n 1)
